import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Temporary placeholder created by the assistant.
/// Replace this file by running:
/// flutterfire configure --project=memoro-f89bf
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPxfOpBIC1ii8e-U3PDBvYTA4OMi1LOVs',
    appId: '1:299115058311:web:136cdff6a92d005b021422',
    messagingSenderId: '299115058311',
    projectId: 'memoro-f89bf',
    authDomain: 'memoro-f89bf.firebaseapp.com',
    storageBucket: 'memoro-f89bf.firebasestorage.app',
    measurementId: 'G-Z2DGC8WDPE',
  );

  // TODO: Replace with real values generated by FlutterFire CLI.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtTvsndBsRfNHqyLxB6QU3BdVWzC67OvA',
    appId: '1:299115058311:android:9ae05d26d5a0eacc021422',
    messagingSenderId: '299115058311',
    projectId: 'memoro-f89bf',
    storageBucket: 'memoro-f89bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMDJWzIynkQ2TDy2WGleI_TVuDZEZvJUw',
    appId: '1:299115058311:ios:9135ebdeb8433b64021422',
    messagingSenderId: '299115058311',
    projectId: 'memoro-f89bf',
    storageBucket: 'memoro-f89bf.firebasestorage.app',
    iosBundleId: 'com.example.memoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMDJWzIynkQ2TDy2WGleI_TVuDZEZvJUw',
    appId: '1:299115058311:ios:9135ebdeb8433b64021422',
    messagingSenderId: '299115058311',
    projectId: 'memoro-f89bf',
    storageBucket: 'memoro-f89bf.firebasestorage.app',
    iosBundleId: 'com.example.memoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPxfOpBIC1ii8e-U3PDBvYTA4OMi1LOVs',
    appId: '1:299115058311:web:c9137fbe1a33f4e2021422',
    messagingSenderId: '299115058311',
    projectId: 'memoro-f89bf',
    authDomain: 'memoro-f89bf.firebaseapp.com',
    storageBucket: 'memoro-f89bf.firebasestorage.app',
    measurementId: 'G-7X0EP2EQ3R',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: 'REPLACE_ME',
    projectId: 'memoro-f89bf',
    storageBucket: 'REPLACE_ME',
  );
}